### ISSUE TITLE
"End of paragraph, no punctuation" error connection to "Beginning of paragraph, lower case" error

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#10]
Are errors of the types "word ends paragraph but no punctuation mark" and "word starts paragraph but in lower case" connected?

I believe that we get two errors for each instance: once for the word that erroneously ends a paragraph, and a second time, that the first word of the next paragraph starts it in lower case. If so, I think merging the paragraphs should remove the second error as well?

**Comment by gsautter** [comment]
As explained on our Skype today, this was a scoping issue with the automated re-checks after edits ... fixed now, comes with next build.
