### ISSUE TITLE
Error: Treatment has broken boundaries

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#13]
Can not determine cause of error. It says the treatment has broken boundaries, I fixed its subsubsections, but error persists.

However, once document is closed, article list shows zero Blockers and Criticals

In: `ejt-541_pauly_noel_sonet.pdf.imf`

**Comment by gsautter** [comment]
Looks like an update issue in the protocol view to me ... will check ... do you happen to have any logs, which could show me if there is some hard exception happening in the background?

**Comment by brokentool** [comment]
here are the logs as of today, but I've worked with the tool this week too, so I do not know if they will be of use

[Logs.zip](https://github.com/gsautter/goldengate-qualitycontrol/files/3578172/Logs.zip)
