### ISSUE TITLE
Bug: Document does not update resolved errors

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#14]
Angel and me edited the same document, consecutively. However upon closing the document, the original errors remain visible in the list of all documents. Closing the list and re-opening it with the console command still shows the same errors we both resolved twice over.

In: `Novelo-Gutierrez, Gonzalez-Soriano - 2003.imf`

**Comment by gsautter** [comment]
OK, this is weird ... what did "Re-Check All" produce? Did the list empty?

**Comment by gsautter** [comment]
Also, do you happen to have any logs that might shed some light on hard errors happening under the hood?

**Comment by gsautter** [comment]
I just did this document, and the only thing I had left to fix was to cut the terminal period of the caption on Page 4 out of the main text stream and append it to the end of the caption. Subtle one, but not sure this is what you are talking about ...

**Comment by brokentool** [comment]
for Logs, [see this error](https://github.com/gsautter/goldengate-qualitycontrol/issues/13). however I do not remember what the "Re-Check" did. apologies.
