### ISSUE TITLE
Error: Broken Geo Coordinates

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#15]
In: `zootaxa.4590.4.2`

MCTaggerOnline does nothing. However, running "Extract material citations" and then "Parse material citations" allows to check parsing, seems correct.

**Comment by gsautter** [comment]
MaterialsCitationTaggerOnline kicks into action only if you run it either on a whole treatment (or document containing one or more treatments) or on a single paragraph ... it's an odd (and pretty old) and counter-intuitive filter, admittedly, but it's noted due for an overhaul anyway. I plan on sharing common logic between the automated "Extract Material Citations" and the manual pair of MaterialsCitationTaggerOnline and MaterialsCitationParserOnline.

**Comment by gsautter** [comment]
By the way, how does your question relate to geo-coordinates (as in the issue title)?

**Comment by brokentool** [comment]
I meant that I still have an error about them being broken, even though looking at the XML, I thought they were parsed correctly.

**Comment by gsautter** [comment]
Could also be there are ones that fail to tag altogether ... I remember there is one with two decimal points in it (most likely a typo), and the "broken coordinates" error also comes up if coordinates are not in pairs.

**Comment by brokentool** [comment]
error does not seem to be there anymore
