### ISSUE TITLE
Error: Taxonomic Key Treatment has broken inner structure

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#17]
Not sure how to deal with this type of error for a taxonomic key

In: `zootaxa.4597.1.1`

**Comment by gsautter** [comment]
This one had overlapping `subSubSection`s, more specifically one had to others nested in it ... the XML view helps a lot here.

**Comment by brokentool** [comment]
I meant I do not know how to proceed with keys at all

**Comment by gsautter** [comment]
Keys can come in two ways: either embedded in a larger treatment, or at the top level, in which case we make them into separate treatments together with their title. The `subSubSection` type is `key` in both cases, and in the latter case, the title is `nomenclature`.

The `subSubSection`s have to cover the whole treatment in both cases, just like everywhere, so in light of "broken inner structure", keys are no different from other treatments.

**Comment by brokentool** [comment]
thanks for the explanation!
