### ISSUE TITLE
Error: Table Caption not assigned to a target

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#18]
Table is not a real table, not even an image. It has a caption for a table, but it's just a catalogue list

In: `zootaxa.4597.1.1`

**Comment by gsautter** [comment]
Which table are you talking about? I just sifted through the whole document, and all the tables in `zootaxa.4597.1.1.pdf.imf` look pretty much like regular tables to me ... sure it is this document?

**Comment by gsautter** [comment]
OK, found it ... must have skimmed over the caption as well ... "TABLE 6" ... this is really an oddjob, not sure how to handle this, but it's most definitely _not_ a table.

I marked the respective errors as data errors for now ... nothing else we could do, I'm afraid.

**Comment by brokentool** [comment]
roger that
