### ISSUE TITLE
Bug: word in lower case starts a paragraph, but is inside a table

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#19]
I got an error that a word in lower case starts a paragraph. However, said word is inside a table and the table is annotated as such. Shouldn't this type of error check ignore tables?

**Comment by gsautter** [comment]
Maybe ... however, even in tables it can be an indicator of some misplaced row split. How often do you have this kind of false positives?

**Comment by brokentool** [comment]
not often, admittedly. just thought I point that out
