### ISSUE TITLE
Bug: "Error running DocumentProcessor"

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#20]
In: `zootaxa.4604.1.5`

While running "Extract material citation" command, got error message "Error running DocumentProcesor", with text: "Error applying Extract material citations: null"

**Comment by gsautter** [comment]
"null" errors and similar things point to something hinky going on under the hood ... please provide the logs in such cases.

**Comment by brokentool** [comment]
sorry, forgot the logs.

[Logs 10-09-2019](https://github.com/gsautter/goldengate-qualitycontrol/files/3595474/Logs.10-09-2019.zip)

**Comment by gsautter** [comment]
OK, found it in the log. However, this one happens in a really strange section of the code, which never ever has caused such trouble before. In particular, some data structure appears to have gone missing, and I'm rather baffled how that might have happened ...
Did you run on the whole document? Or on single `treatment` or `subSubSection`? In the latter case, it would be very helpful to know which, so I can reproduce and fix this.

**Comment by gsautter** [comment]
OK, found it, and was able to reproduce it. Now checking what exactly goes wrong ...

**Comment by gsautter** [comment]
Got it, at least I think ... put some preventive measures into place, comes with next update.
