### ISSUE TITLE
Bug: MCitation boundaries within the same Subsubsection return "end paragraph without punctuation" error

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#22]
Basically, title. In: `zootaxa.4602.1.1`; also in: `zootaxa.4603.1.10`

I had several errors "Word ends paragraph but is no punctuation mark" for words that end separate **material citations** within the same paragraph. Left two of these unresolved for you to see

**Comment by gsautter** [comment]
Are the "paragraph" _regions_ really the same (not what you would _read_ the text block like)? If not, merging the "paragraph" regions (drag a box around them and select "Merge 'paragraph' regions") should fix it.

Background: especially in materials citations, the right edge of a justified paragraph isn't always a flush as you would hope, so sometimes there are phantom paragraph breaks.

**Comment by brokentool** [comment]
I have like 3-4 of these errors within the same paragraph. The end of each separate MCitation is considered as the end of the paragraph. You can see for yourself in the mentioned documents, when you can

**Comment by gsautter** [comment]
Could you give me a page number or treatment taxon to search for? Would make it way easier to spot what you're referring to ...

**Comment by gsautter** [comment]
Found the errors in `zootaxa.4602.1.1`, and they are _really_ weird ... however, I tried "Re-Check", and they disappeared. Will have to check how they emerged in the first place, but I'm afraid this might be a really hard one to reproduce ...

**Comment by gsautter** [comment]
I could reproduce it in `zootaxa.4603.1.10`, however, and the XML view shows why:
![image](https://user-images.githubusercontent.com/5789714/64669215-09a16880-d461-11e9-9b71-0c067d569fea.png)
I have no idea how these paragraph breaks got in there (some in mid line), but they did exist, and thus the reported errors are indeed there. "Next Word Relation" on the words in question fixes this swiftly, though, as will "Tools -> Check Text Flow Breaks".
