### ISSUE TITLE
Error: lacking holotype for taxon

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#24]
In: `zootaxa.4603.3.9`

Can not Extract or Parse material citations. Can not run Tagger or Parser in XML view.

**Comment by gsautter** [comment]
Which XML view did you open? Of the whole `treatment`, or one `subSubSection`? In the latter case, how many `paragraph`s does the `subSubSection` contain?

Background: for legacy reasons (I'm aware I have to rework this), the interactive materials citation tagger and parser work either (a) on a whole `treatment`, or (b) on a single `paragraph`. That means if you open a `subSubSection` with two or more `paragraph`s in it, the two gizmos won't do anything.

There is two ways around this: (1) open the XML view for the whole `treatment`, or go from the `subSubSection` and open an individual `paragraph` in a sub view (the XML views are recursive).

**Comment by brokentool** [comment]
it was my fault. I forgot you can manually annotate a MC as well as other elements. error was fixed yesterday
