### ISSUE TITLE
Bug: Image not present in document

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#25]
In: `zootaxa.4612.3.4`

Error for caption of Figure 3 not being assigned to a target. However, no image is present above the caption.

**Comment by gsautter** [comment]
Looks like something went wrong in image decoding, will check and get back to you.

**Comment by gsautter** [comment]
Turns out the figure decodes just fine ... this is a rendering problem, will figure it out.

**Comment by gsautter** [comment]
Fixed ... was a clipping issue with a figure rendering to the upper right and then rotating 180° into its display position ... sounds weird? Well, it is ... one more obfuscation technique broken.

I also fixed the page image, then the error in the protocol, and updated the IMF on the server.
