### ISSUE TITLE
Suggestion: do not remove highligh of current document in the list upon closing it

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#26]
Clarification: when you close a document, its highlight in the full list of documents is removed. This is not a major issue, but it would be helpful for the highlight to remain

**Comment by gsautter** [comment]
Well, that's a UI thing ... if you remove the selected row in a table, that clears the selection ... possible to get around, but a bit tricky. Where would you like the highlight to go? The row above the removed one, or the row below? And what to do in case the top-most or bottom-most row is removed?

**Comment by brokentool** [comment]
To be fair, I think that a row is removed not that often, at least in my experience, since we do not fix Majors and Minors.

Otherwise, I do not mind either way - **above** or **below**, preference for **above**. When top-most is removed, highlight current top-most. Same for bottom-most?

Anyway, this is just a suggestion and not an important one at that. I would just find it easier to "remember" my place in the list with the highlight not disappearing

**Comment by brokentool** [comment]
Also, I'm perfectly fine with the highlight disappearing when the row is removed upon closing, but remaining if the row remains as well.

**Comment by gsautter** [comment]
OK, that's pretty doable, I'll add that soon as I get around to it.

One more thing: how should the selected row behave if you change the sorting of the list (click on one of the column headers)? Stay in the current position, or stick with the selected row?

**Comment by brokentool** [comment]
stick with the row sounds more intuitive, but I have no preference to be honest

**Comment by gsautter** [comment]
Sounds more intuitive to me as well ... I'll do it that way.

**Comment by gsautter** [comment]
Done, really a good addition to the document list widget, thanks for the suggestion. Comes with next update.
