### ISSUE TITLE
Multiple Logins?

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#28]
Happened in: `zootaxa.4617.1.1`

Me and Angel were in this document at the same time. How is this even possible?

**Comment by gsautter** [comment]
Simple ... you use the same login. The lock is assigned to a user name, so if you both log on with the same one, such a situation can happen.

I can easily create dedicated accounts for each one of you. Most likely I should do that, if for the name that shows up in the treatment page ... but ultimately, you should be there anyway. Mailed you the logins.

**Comment by brokentool** [comment]
not sure where to use the login?

**Comment by gsautter** [comment]
In `auth=<userName>:<pwd>` in the DOS command.

**Comment by brokentool** [comment]
successful!

**Comment by brokentool** [comment]
could you please set up a login for Angel as well?

**Comment by gsautter** [comment]
I did, and mailed it to him.
