### ISSUE TITLE
Bug: after last update, document list flips on closing of document

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#29]
Basically, title. Every time you close a document, the list flips from `A --> Z` to `Z --> A`

**Comment by gsautter** [comment]
Thanks for noticing ... will investigate.

**Comment by gsautter** [comment]
Got it ... the list gets re-sorted when it's modified, by the current sort column, and a click on a column header also sorts the list. Now a second click on the column header is supposed to revert sort order, but re-sorting after an update surely never was. Distinguishing the two cases now, comes with next update.
