### ISSUE TITLE
Bug: Document List does not load

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#3]
After loading Local.Default configuration, can not load document list. I get the error message:

"An error occurred while loading the document list: null"

![scrn04](https://user-images.githubusercontent.com/22291049/62598854-4e326500-b8f3-11e9-90cd-6cb58e468a5d.png)

**Comment by gsautter** [comment]
My bad ... fixed ... was one component in the server that had slipped the update ... should work again now.
