### ISSUE TITLE
Zooming in changes currently viewed page

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#30]
Just thought I'd point that out: when I zoom in, my view is moved from the current page I'm on, to several pages down (i.e. I zooming in on page 286 moved me to page 292). Is there a way to avoid this?

Not sure if number of pages in document matter for how far down one's view is moved.

**Comment by gsautter** [comment]
I don't think it's the number of pages outright, but how many pages you've scrolled down ... most likely position memory becomes imprecise at some point ... will investigate.

**Comment by gsautter** [comment]
Got it ... changed the computation now to use the centered page as an anchor, and that works spot-on. Comes with next update.
