### ISSUE TITLE
Error: broken geo coordinates; broken boundaries

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#31]
In: `zootaxa.4617.1.1`

Currently there are 4 critical errors in this document. One is for broken coordinates, three are for treatments with broken boundaries.

Was not able to determine reason for these errors. Resolved similar ones in this document, but I'm stuck with these four. Requesting assistance

**Comment by gsautter** [comment]
Got the coordinates ... MC "Type material ..." somehow wrapped around the whole `subSubSection`, most likely as the result of some nesting issue, and as a result ended up having 3 coordinate pairs. Correcting the boundaries fixes it.

**Comment by gsautter** [comment]
Two of the "broke treatment boundaries" were due to lack of a paragraph break in "Latin, adjective, cristatus, crested). Antichiropus cucumeraceous Car, n. sp." before "Antichiropus", so there was one logical paragraph running from the end of one treatment into the start of the next.

**Comment by gsautter** [comment]
The third treatment with "broken boundaries" was the very same, only that in this case the subsequent treatment had been lost to some text stream issue. Fixed both now.
