### ISSUE TITLE
Error: treatment has broken boundaries

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#32]
In: `zootaxa.4619.2.8`

This one, again. There are 3 broken treatment boundaries errors. Treatments are very short, but was not able to determine cause of error. Tried looking at the MC, paragraphs and Sssections in XML, but was not able to find it.

Apologies for all these similar issues, but I still struggle with some types of errors

**Comment by gsautter** [comment]
This one had similar issues as the one in #31, but also terminal periods somehow cut off paragraphs. After fixing these text stream gaps, I extended the `subSubSection`s and `treatment`s to include these periods, and then the errors were gone. Especially those split-off periods are hard to spot at 100% zoom, also on "broken paragraph boundaries", so please zoom in when you check the latter to make sure you don't overlook a period.

**Comment by brokentool** [comment]
I actually thought I did. Meaning, I zoomed to the end and highlighted Ssections and MCs, but somehow missed that
