### ISSUE TITLE
Bug: text flow breaks when taxonomic key end a page

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#33]
I noted a few of these: when a taxonomic key ends a page, its last couplet is marked as a footnote (I would guess because of its position on the page and starting with a digit)

![scrn08](https://user-images.githubusercontent.com/22291049/64960946-12e56780-d89d-11e9-9500-bc139513dd24.png)

**Comment by gsautter** [comment]
You guess correctly ... and it's a really hard one to catch, as footnotes are far more common a concept as taxonomic keys.

Also, I assume you might be getting conflated paragraphs due to the key lead not ending in a punctuation mark?

**Comment by brokentool** [comment]
yes, this is the way I actually encounter these errors

**Comment by gsautter** [comment]
I'll try and think of something ... the "footnote" false positives might be avoidable by insisting in a drop in font size of the footnote as compared to the main text, as well as a minimum distance from the latter, or maybe a combination of both ... have to test this. Footnotes are in general a bit hard because contemporary articles hardly ever contain any, so examples are scarce.

**Comment by gsautter** [comment]
Which document is this, by the way? would be good to have a test case for the filter ...

**Comment by brokentool** [comment]
I will provide you with the next document that has this bug, as previous ones I've encountered, I've fixed already

**Comment by gsautter** [comment]
Fixed or not ... if you remember one or two of them, I can still re-create the error an run a some test.

**Comment by brokentool** [comment]
sorry.. will have to encounter again to give you a document ID

**Comment by brokentool** [comment]
found an example in: `zootaxa.4629.4.1` page 455

also: `zootaxa.4629.4.3` page 548

**Comment by gsautter** [comment]
Fixed ... added a catch now that requires footnotes to be in a separate block of their own, and the whole block has to be in the footnote area of the page.

I corrected the two documents as well, thanks for hinting me to these test cases.
