### ISSUE TITLE
Bug: Title of article in Chinese appears garbled

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#34]
See attached screenshot. Title is in Chinese. In: `zootaxa.4624.1.10`

Also, not sure if important, but seen this for the first time and decided to put it here.

![scrn09](https://user-images.githubusercontent.com/22291049/64963117-60fc6a00-d8a1-11e9-8e34-6b852f4b1c65.png)

**Comment by gsautter** [comment]
Hard one ... I don't think we even can address this right now, as we don't have anyone around who even reads Chinese ... also, considering Mandarin in font decoding merely for the handful of cases we encounter would be absolute overkill, as it would slow down font decoding really badly. On top of that, the baseline fonts used for comparison don't have any glyphs (character images) for these Unicode points, so they are impossible to verify ... not sure what to do here.

**Comment by brokentool** [comment]
I understand. I just wanted to point this out, not really a problem for me.
