### ISSUE TITLE
Suggestion: "Esc" key to work as "Cancel" option in dialogue windows?

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#35]
Is this possible?

I believe it will help us save time in the long run, not having to click Cancel every time, but using Esc

i.e.: Attributes window, XML view, etc.

**Comment by gsautter** [comment]
Catching key strokes on a window level is a hard thing to do, so as usually window _content_ components like text fields have the keyboard focus. Will have to see what I can do.

**Comment by brokentool** [comment]
just something I thought of. I don't think it should be a priority or anything

**Comment by brokentool** [comment]
closing this one
