### ISSUE TITLE
Error: MC has broken boundaries

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#36]
In: `zootaxa.4629.1.10`

For the life of me, I could not find how the boundaries are broken

**Comment by gsautter** [comment]
Fixed it ... the error message was due to two `specimenCount` annotations, one of them around "474 m." ("m." for "males") in "474 m.a.s.l." this is a somewhat frequent error, but hard to prevent in the absence of actual "male" symbols, as "male" sometimes _is_ abbreviated as "m".

**Comment by gsautter** [comment]
Also, for some reason you might have lost a "missing holotype" error, which showed up again when I used "Re-Check All". Fixed that as well.
