### ISSUE TITLE
Bug?: Pictorial Key

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#42]
In: `zootaxa.4648.1.3`

See the five critical text stream errors left.

First time I see a "Pictorial Key". It has huge black rectangles where I'm not sure if images or text is missing, or this is how they did it.

If latter, kudos to layout team for creating the single most weird layout I've ever seen

**Comment by gsautter** [comment]
This kind of key is completely new to me, never seen anything like it ... I simply marked the whole diagrams as images now (which is what I think they are anyway), so QC ignores the ostensible text flow errors inside.
