### ISSUE TITLE
Suggestion: Hihglight MC when selecting errors from its category

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#45]
Currently, when an error from the MC category is selected, the MC button on the right does not tick automatically. This does happen for other categories.

![scrn15](https://user-images.githubusercontent.com/22291049/66042611-98b41480-e525-11e9-8830-1cb09c82e7f9.png)

**Comment by gsautter** [comment]
Good idea ... but actually something that _should_ already work, and most likely does for other types of errors ... or doesn't it? Anyway, this is more like a bug in the error subject highlighting functionality ("error subject" being the annotation, region, or word the error refers to).

I'll look into it.

**Comment by brokentool** [comment]
> This does happen for other categories.

I can't think of another category where it does not work. On the contrary, some errors, when selected, highlight multiple categories on the right and I usually turn off most of them.

**minor offtopic**: I have never, ever needed nor used the "emphasis" category, but I get it highlighted with some categories. Can it be safely removed from automatic highlighting? **/offtopic**

**Comment by gsautter** [comment]
I'd rather keep highlighting the `emphasis` elements because they sometimes incur nesting issues ...

**Comment by gsautter** [comment]
Got it ... the reasons that the `materialsCitation`s don't show automatically is that the error check actually goes for `paragraph`s that _contain_ materials citations with broken boundaries. Which kind of makes sense because re-tagging `materialsCitation`s is something you do on the `paragraph` or `subSubSection` level.

I'll try and figure out a way of making the `materialsCitation`s show anyway.

**Comment by gsautter** [comment]
Found it's very possible to highlight _all_ annotations involved in the error checking expressions. However, this tends to light up a whole Christmas tree for certain error types, i.e., all sorts of annotations. We'll have to evaluate whether or not that makes your lives easier ...
