### ISSUE TITLE
Treatment lacking holotype for comb. nov and gen. nov

### ISSUE THREAD

**Issue by angel-s-slavchev** [gsautter/goldengate-qualitycontrol#46]
This is a regular false positive. It is easy to mark as such in the document, but at some point it could be filtered out when the document is analyzed.

**Comment by gsautter** [comment]
We're already working on this, namely that an original description above the rank of species requires a type taxon rather than a holotype. "type taxon" being the type species of a genus, the type genus of a family, etc.
