### ISSUE TITLE
Error: material citation boundaries are broken

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#5]
I do not know how to deal with this error, I believe this is the first time I'm seeing it.

In document: zootaxa.4590.2.4

**Comment by gsautter** [comment]
See #4 ... another set of rules that were newly added. They check for duplicate details in MCs (e.g. countries, regions, dates, coordinate pairs) as a hint of some MC split having been missed.

The same set of rules also checks for single coordinates, enforcing they always come in pairs.

**Comment by gsautter** [comment]
My general way of dealing with this is to use the XML view of the MC `subSubSection`, and then "Tools -> Run Analyzer -> MCT.MaterialsCitationTaggerOnline" and after that "Tools -> Run Analyzer -> MCT.MaterialsCitationParserOnline". If this is too much effort right now, you might also ignore these errors. The error protocol preview should enable you to see which categories the criticals and blockers are in.

**Comment by gsautter** [comment]
The ultimate goal is to have a comprehensive QC, but if it turns out too much hassle or an over-emphasis of the area, I'll simply reduce the MC errors to majors in one of the next updates ... subject to discussion, I guess.
