### ISSUE TITLE
Multiple missing authorities

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#52]
My sincere apologies, I know we've been over this already, but I forgot the method for editing attributes of multiple taxonNames simultaneously and I can not find my notes on this.

Case in point: 62 missing authorities with a lot of duplicates.

In: `zootaxa.4681.1.1`

**Comment by gsautter** [comment]
Go "Edit -> List Annotations" and enter `taxonomicName[not(./@authorityName) and not(./@baseAuthorityName)]` as the filter, then switch to "Highlight Matches", sort lexicographically by clicking on the "Value" column header, select all the duplicate names (one group at a time), and use "Modify Attribute"

**Comment by brokentool** [comment]
success!
