### ISSUE TITLE
Can not annotate Table

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#53]
In: `zootaxa.4687.1.1`

I'm guessing because it's a "real table", maybe just text, formatted to look a bit like a table.

![scrn20](https://user-images.githubusercontent.com/22291049/68028485-b4920e00-fcbd-11e9-975c-84813929b567.png)

**Comment by gsautter** [comment]
You're guessing right ... hard to tell why people call such a listing a table ... maybe to facilitate referencing it from elsewhere in the text.

As to the underlying logic: GGI refuses to mark a table if it cannot find at least two distinct columns.

**Comment by gsautter** [comment]
So basically this one is somewhere in between a false positive and a data error.
