### ISSUE TITLE
Error: Caption not assigned to target

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#54]
In: `ejt-570_shipunov_gladkova_timoshina.pdf`

Figure caption not assigned to target, however target is not a real image. On page 6 of article

**Comment by gsautter** [comment]
Not an `image`, but a `graphics`, and they handle the same. The two types exist to distinguish (mainly) bitmap figures (`image`) from (mainly) vector based figures (`graphics`), with the latter rendering via PDF native vector drawing instructions, no very different from SVG.

**Comment by brokentool** [comment]
never used "graphics" until now. thanks for explaining
