### ISSUE TITLE
Illustrations with non-standard captions

### ISSUE THREAD

**Issue by angel-s-slavchev** [gsautter/goldengate-qualitycontrol#58]
Osborn1906Tyrannosaurus.pdf.imf

This paper is quite old and has a rare problem - a number of plates in which the label is separate from the caption itself - see the attached screenshots (label 'Plate XXXIX' is on the top right, the caption is below the image).
Is this to be treated as 'False positive/Data error'?

![j35ZcVRKjM_cr](https://user-images.githubusercontent.com/44800901/69971509-ab989480-1528-11ea-9da3-f755204ec1fa.jpg)

**Comment by gsautter** [comment]
You're right, this is a good bit of an oddjob ... in fact, a good bunch of such old publications are ... treating this as a "False Positive / Data Error" would be one way of handling this, yes. The other would be to connect the captions and merge them into one, most likely starting with "Plate XXX" and then connecting to the more comprehensive label. The latter would also work better for figure citations (if there are any).
