### ISSUE TITLE
An unknown type of text demarkation

### ISSUE THREAD

**Issue by angel-s-slavchev** [gsautter/goldengate-qualitycontrol#59]
paper:
zenodo283229
![caYcDalBvZ_cr](https://user-images.githubusercontent.com/44800901/70058224-2de78e00-15e7-11ea-9cb2-9397517c5b92.png)

A two-column paper, on one page of the references one of the columns was not included in the text flow.
I failed to do it manually, as I can not figure out what the text is actually marked as.

**Comment by gsautter** [comment]
This dark gray text color indicates "artifact" words ... the "artifact" text stream type is usually intended for OCR hallucinations (e.g. speckles on the page "recognized" as some punctuation mark), so hard to tell how this happened here ...

**Comment by gsautter** [comment]
I repaired the text flow for you and marked all the references inside the problematic section. Here's how I did it:
- show text streams, blocks, and paragraphs
- drag a box around the problem column and use "Order Stream" (connects all the selected words into a text stream, in reading order)
- select the whole new text stream and use "Merge Paragraphs" (irons out the paragraph breaks after each word)
- click inside the block and use "Revise Block Paragraphs" (marks the actual paragraph breaks)
- use "Make Successor" as used to to splice the problem section into the main text
