### ISSUE TITLE
Error: MC boundaries are broken

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#63]
In: `zootaxa.4695.3.4`

Only Critical left in document. Could not figure out what is wrong, checked XML view of treatment, with paragraphs and subSubSections highlighted, but could not find it

another such example in: `zootaxa.4695.4.8`, only Critical left

**Comment by gsautter** [comment]
The error in `zootaxa.4695.3.4` is a false positive, incurred by the repetition of the "male" symbol in the label quote ... flagged as such.

The error in `zootaxa.4695.4.8` is also a false positive, incurred by a second country ("Hungary" in "(coll. Peter Gyulai, Miskolc, Hungary), later to be deposited in the Hungarian Natural History Museum (Budapest, Hungary)") ... removing the spurious annotations in the latter test passage fixed it.
