### ISSUE TITLE
Error: Treatment with broken inner structure

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#7]
In documents: `zootaxa.4587.1.1` and `zootaxa.4588.1.1`

for your consideration

**Comment by gsautter** [comment]
`zootaxa.4587.1.1` has a treatment with a broken _inner_ structure, aka incomplete or invalid `subSubSection`s ... fixed it, but the one I was actually interested in was about invalid treatment _boundaries_ ... do you remember which one that was?

**Comment by gsautter** [comment]
`zootaxa.4588.1.1` indeed had broken treatment boundaries ... one treatment simply failed to include the terminal period (happens on manual extension, especially if you don't zoom in), and the other had some text cut off an image, but wasn't properly marked as a block with lines and paragraphs.

**Comment by gsautter** [comment]
The 500+ text stream issues in `zootaxa.4588.1.1` were actually not all false positives or treatment headings. There were well over 150 actual issues, mostly owing to page breaks or extremely small blocks (4 lines or fewer), which quite sometimes don't provide a sufficiently large or coherent sample for reliable paragraph identification.
