### ISSUE TITLE
Error: Reference does not have an ID

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#72]
in: `37231-40323-1-PB.pdf.imf`

Not sure if we covered this, apologies if we did, but I do not know how to resolve this type of error

**Comment by gsautter** [comment]
Please try and re-run "Tools > Mark Bibliographic Citations" ... that gizmo establishes the links between the bibliographic references and the respective citations, and also add the reference IDs for that purpose.

**Comment by brokentool** [comment]
this did the trick, thanks

**Comment by brokentool** [comment]
I found a document, where when I try to use "Tools > Mark Bibliographic Citations" it warns me that "this document does not seem to be fit for Mark... and will produce undesired results". This is the first time I see such a warning. Did not proceed with the function.

in: `NeotropIchthyol.17.1.180099.pdf.imf` see only critical error left

**Comment by gsautter** [comment]
That warning simply occurs if references have been parsed by the batch, but not double checked by a user ... nothing to worry about, it's more of a warning for users doing ad-hoc generic PDFs, not template backed batch runs ... so you can simply go ahead.
