### ISSUE TITLE
Bug: Zooming in at 300% hides second column of text on page

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#73]
in: `ActaEntMusNatPra.58.1.21-24.pdf.imf`

When I zoom in at 300%, I can not scroll horizontally to the second column of text on the page.

![scrn24](https://user-images.githubusercontent.com/22291049/75145716-2b866300-5702-11ea-9dd6-141b1d72bceb.png)

**Comment by gsautter** [comment]
OK, this is weird ... could you try and resize the whole window a little bit and see if the scroll bar adjusts to the actual display width? Could be a one-off glitch ... at least I've never seen anything to this avail before.

**Comment by brokentool** [comment]
upon opening thew document, and zooming to 300%, the bug did not occur
