### ISSUE TITLE
lacking holotype - unresolvable in a non-english paper

### ISSUE THREAD

**Issue by angel-s-slavchev** [gsautter/goldengate-qualitycontrol#74]
lheringia-1-.53-61

Two tratments with clearly marked and fully parsed material citations. In both the 'lacking a holotype' does not go away. I presume it is becvause the text is 'Holótipo'.
![oeFPjcejiv](https://user-images.githubusercontent.com/44800901/75146703-4ce84e80-5704-11ea-9912-901122d274a7.png)

**Comment by gsautter** [comment]
Try and change the `typeStatus` attribute to "holotype" via "Edit Materials Citation Attributes" ... the type status normalizer doesn't understand Portuguese just yet ...

**Comment by angel-s-slavchev** [comment]
I tried it on another paper and it worked.
