### ISSUE TITLE
Bug: stretched out symbols

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#75]
in: `NeotropIchthyol.17.2.e180038.pdf.imf`

see three critical errors in Illustrations category. Tried the "Change font" option, but couldn't fix

**Comment by gsautter** [comment]
`FFB3FFBEAF32FFC8FFB0FFAB031CFFE0` ... thanks for looking this document ... this way I'll be never able to do about this error.

**Comment by brokentool** [comment]
also in: `NeotropIchthyol.17.1.e180165.pdf.imf`

**Comment by gsautter** [comment]
Thanks for letting me know you meant Table 1 in `NeotropIchthyol.17.2.e180038.pdf.imf` ... searching is fun.

**Comment by gsautter** [comment]
This looks like a problem with the word boundaries rather than a font issue ... appears to affect pages that are in top-down direction in the original PDF ... will investigate.

**Comment by brokentool** [comment]
> 
> 
> `FFB3FFBEAF32FFC8FFB0FFAB031CFFE0` ... thanks for looking this document ... this way I'll be never able to do about this error.

I did not understand this

> 
> 
> Thanks for letting me know you meant Table 1 in `NeotropIchthyol.17.2.e180038.pdf.imf` ... searching is fun.

or this

I thought "see three critical errors in Illustrations category" should point you in the right direction, and in the second one, it was only the one crit?

**Comment by gsautter** [comment]
> > `FFB3FFBEAF32FFC8FFB0FFAB031CFFE0` ... thanks for looking this document ... this way I'll be never able to do about this error.
> 
> I did not understand this

As long as you have a document open, you hold the lock, and I cannot open it to even look into the error ... most likely you had already closed it when you saw my replay ...

**Comment by gsautter** [comment]
> > Thanks for letting me know you meant Table 1 in `NeotropIchthyol.17.2.e180038.pdf.imf` ... searching is fun.
> 
> or this
> 
> I thought "see three critical errors in Illustrations category" should point you in the right direction, and in the second one, it was only the one crit?

"Misfigured Fonts" is not something the QC checks for, as it's mostly a rendering issue, which is why looking at the error log never crossed my mind ... sorry for the misunderstanding.

**Comment by brokentool** [comment]
I'll keep that in mind. Also to point out the error's place more precisely

**Comment by gsautter** [comment]
> I'll keep that in mind. Also to point out the error's place more precisely

Thanks :-)

**Comment by gsautter** [comment]
Anyway, figured it out ... was a stupid error in word distance computation for top-down font direction ,,, fixed now, comes with next build.
