### ISSUE TITLE
Question: Mcs outside of treatments

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#76]
in: `JNATHIST.53.25-26.1585-1606.pdf.imf` page 16/22

It just occurred to me, why are there MCs outside of treatments? This is not something I see every day, but I have definitely encountered similar cases before

**Comment by gsautter** [comment]
Not sure ... the fully automated gizmo only ever marks MCs inside treatments, so I tend to think these were annotated manually at some point, or treatment boundaries were moved with the MCs left behind ... most likely a look at the version history of the document might shed some light.

**Comment by brokentool** [comment]
here is another case, in Materials and Methods. in: `JNATHIST.53.23-24.1401-1420.pdf.imf` pages 2 and 3

**Comment by gsautter** [comment]
Again, it's highly unlikely the batch marked these MCs, as it only ever targets treatments ... it is quite possible the guys in Porto Alegre marked them manually ... not a QC thing, rather a process and specification issue.
