### ISSUE TITLE
Holotype can not be assigned to treatment section

### ISSUE THREAD

**Issue by angel-s-slavchev** [gsautter/goldengate-qualitycontrol#78]
JNATHIST-53-25-26.1533-1584.pdf.imf

Some threatments refuse to accept holotype designations.
Example:
Pleuriocardia (Incacardium) schneideri sp. nov on p.18; second error in the treatments error section
I added the material citations section, parsed it, then made sure the type status attrubute says 'holotype' (as opposed to 'holotypei', as it was OCR-ed)
Still can not get the treatment to accept the holotype.
![xdb1OSTOrR](https://user-images.githubusercontent.com/44800901/75343418-198ef680-58a1-11ea-9783-4823ac6a2866.jpg)

**Comment by gsautter** [comment]
First thing, click on "Holotypei" and use "Edit Font" to correct that mis-decoded comma. Second, you go open the XML view of the treatment and go "Edit > Run Pipeline > MaterialsCitationExtractor.pipeline" ... that should fix it.
Ultimately, you have to re-run the materials citation extractor after correcting the font, so the former has a chance to pick up the corrections made to the latter.

**Comment by angel-s-slavchev** [comment]
The problem turned out to be something else that I haven't noticed - the tratment was split into two right before the materials section.
