### ISSUE TITLE
Error: part of caption not in text stream?

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#79]
not sure how to handle this one. it appears that the whole document has OCR issues.

please see screenshot for document name and error location. figure 4 has the issue, where the word "fig" is not marked as text at all, thus I do not know how to resolve the three Crits for figure citations.

![scrn27](https://user-images.githubusercontent.com/22291049/75853585-23f84580-5df7-11ea-983e-faec3c92bfd6.png)

**Comment by gsautter** [comment]
To mark missing words, click in the page edge and select "Edit Page Image & Words", then select the "Mark Words" tool and drag a box around the missed word to mark it.

The figure proper you can mark using "Mark Image" as used to.
