### ISSUE TITLE
Connecting a bibRef Citation to its bibRef

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#8]
I can not link an existing `bibRef citation` to its respective `bibRef`. Even after reading the step-by-step guide we made here. How should I do that?

in document: `zootaxa.4323.4.1`

**Comment by gsautter** [comment]
Which citation are you talking about, just so I know what to look for ...

In general, I'm aware that bibliographic citations require better handling, akin to figure and table citations. However, there are some technical complications to solve ... working on it.

**Comment by gsautter** [comment]
Found it ... most likely, anyway ... that lone "b" on the first page. The trick is this:
- find the reference and "Copy Attributes" to the citation
- go back to the reference, select all of it and "Copy Text", and then put that it into the `refString` attribute of the citation
