### ISSUE TITLE
Question: Lacking holotype, article not in English

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#84]
in: `adansonia2020v42a6.pdf.imf`

Can't figure out how to resolve the lacking holotype error in this one

**Comment by mguidoti** [comment]
@Carol-Sokolowicz 

You were the [first uploader](http://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.name+doc.uploadUser&groupingFields=doc.uploadUser&FP-doc.name=adansonia2020v42a6.pdf.imf&format=HTML) of this one. Could you please take a look on what Veselin is reporting?

Thanks

**Comment by Carol-Sokolowicz** [comment]
Typus is the holotype in this case. It wasn't marked as such, I fixed it.
