### ISSUE TITLE
Error: 600+ "citation not linked to reference" errors

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#85]
in: `AMNH_Bulletin.415.pdf.imf`

these appeared after I resolved the missing reference ID errors. I used Tools --> Mark bib citations and then Tools --> Parse bibliography

Please advise for a non-manual approach

**Comment by mguidoti** [comment]
I'll leave this one with @flsimoes, which from us, it's the most advanced user as right now. 

What do you think, Felipe?

**Comment by flsimoes** [comment]
Will have a look!

**Comment by flsimoes** [comment]
@brokentool do you have the UUID for this one?

**Comment by mguidoti** [comment]
@flsimoes you can get it using TB Article Stats from the Document name: 
![image](https://user-images.githubusercontent.com/44419136/82052379-e8e57e80-9691-11ea-8dc2-9e5de35e82a3.png)
http://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.name&groupingFields=doc.articleUuid&FP-doc.name=AMNH_Bulletin.415.pdf.imf&format=HTML

Here it's: `735C952FFFCAB1543860CC2CB35C6E75`

**Comment by flsimoes** [comment]
So, I can't pinpoint exactly what is causing these errors, but you did the right procedure.
What caught my eye though, is the presence of some bits of text which are considered Artificats (see black boxes in the images below):

![image](https://user-images.githubusercontent.com/3343086/82053875-71fdb500-9694-11ea-957a-52b64db87cbd.png)
![image](https://user-images.githubusercontent.com/3343086/82053885-77f39600-9694-11ea-9955-cb945d8c5db7.png)

There were also 2 references that weren't marked (I fixed this now).

The only way I could make the errors disappear was to copy the attributes from the bibRef to the respective bibRefCitation. But of course this is definitely not the way we should be solving these problems (unless it's a single error on a paper).

Apart from that, we would need to check with Guido.

**Comment by mguidoti** [comment]
@gsautter is watching us, soon he will be able to give his input in the matter.

**Comment by gsautter** [comment]
This is looking outright catastrophic ... all these artifacts ... need to check out how they get marked and why ... the bibliography tagger not working properly is most likely a downstream effect.

One thing that does jump my eye is the intermediate headings embedded in this bibliography, so it might end up treated as a normal enumerated and numbered bulletin list.

**Comment by flsimoes** [comment]
Yes, it is very problematic. These two pages were the only ones with clear artifact block, but I believe there are some female/male symbols across the board that are also marked as artifacts.

**Comment by gsautter** [comment]
Left to wonder what went wrong with this one, and especially where in the process ... I mean, one of the gizmos must have _caused_ this mess ... which means I need to spend some serious time with some cleanup routine.

**Comment by gsautter** [comment]
Just as a hint for repairing those "artifact" false positives: dragging a box around the whole column and using "Order Stream" should at least turn them into a single "main text" test stream in a single action, representing an efficient way of re-integrating the "artifacts" into the main text. "Revise Block Paragraphs" then should help to restore paragraph structure in another single action if required.

On a different note, the more I think about it, it might well be low quality OCR that leads some gizmo to mistake these stretches of text for artifacts in the first place ... or is this PDF born-digital? Anyway, could you share the IMF somehow? I need to figure out what marks these "artifacts" in the first place ...
