### ISSUE TITLE
Can not open context menus in QC tool

### ISSUE THREAD

**Issue by brokentool** [gsautter/goldengate-qualitycontrol#86]
Hi Guido, today when I tried to work on the first ZooKeys article [`ZK_article_1925`], I could not open any contextual menus when clicking on the pages of the document.

I resolved a few text stream errors applying **False positive/Data error**, and then went on to tackle a reference error, but when I left or right click in the reference, no menu appears.

Opened next document, `ZK_article_1926` - same thing. Tried a doc. from a different journal, with the same result.

I updated the tool prior to use, same as ever. This has not happened to me until now

**Comment by brokentool** [comment]
one more thing: if I click and hold down the left mouse button inside a word, and then drag to the right, in order to select multiple words, instead it draws the red rectangle as if I have clicked into white space

edit: even when I drag the red rectangle around, say, a caption of a figure, no menu pops up

**Comment by brokentool** [comment]
has anyone else, by any chance, experienced this before?

@mguidoti @flsimoes

**Comment by flsimoes** [comment]
I haven't seen anything like that myself, if memory serves.

Is it happening all the time now? Or is it in a specific document?

**Comment by mguidoti** [comment]
Same here, @brokentool, that's new to me.

**Comment by brokentool** [comment]
happens absolutely everywhere. no menus pop up whatsoever.

and when I try to select multiple words, even though I have clicked inside a word, it starts to draw the red box, instead of highlighting multiple words

**Comment by flsimoes** [comment]
You might want to recheck your installation.
Yesterday we had to re-install GGI in one of our PCs because it was missing a feature in the template editor (it was a specific case where the PC hadn't been updated gradually over the last 3 months, but still).

1) regarding the menus, I really don't know how to help, probably need to ask Guido directly
2) about the text, I did have 2 instances where I had a somewhat similar problem, but it wasn't a bug. Turns out some fonts are a bit annoying in the sense that if you click within a word, but on the blank space between letters (or within, such as the letter "O") than it doesn't count as actually clicking the word itself. Also, try having "Word Flow" on the Display Control (you most likely have that on already, but I had to say it, just in case).

**Comment by brokentool** [comment]
thanks for the info! I too have not updated for some time, as we were busy as hell here during the quarantine.

@flsimoes may I ask how to go about rechecking the installation, as I haven't had the need to, until now

**Comment by flsimoes** [comment]
The simplest way of doing that, since you haven't updated in a while (normally GGI would update normally), would be to delete your current installation (move it to the Recycle Bin for now), download GGI again (http://plazi.org/resources/treatmentbank/goldengate-editor/) and unzip the new version to the exact same folder/destination as the current installation. That should do the trick.

I'm pretty sure you won't need to back up anything, as you don't work with templates (I think).

**Comment by brokentool** [comment]
thanks! will try this later tonight and report.

**Comment by brokentool** [comment]
did not work, unfortunately. when I tried to start the QC tool with the console command I use, it said it could not find it

also, um, my folder is apparently 44 GB. 0_o

I also noticed that when it asks for a configuration in the beginning, there are only two options (with the installation from your link), while I have 4 options

![Untitled](https://user-images.githubusercontent.com/22291049/84409896-7d51eb00-ac16-11ea-8df9-26400561aa77.png)

**Comment by brokentool** [comment]
for reference, this is the install from the link:

![Untitled1](https://user-images.githubusercontent.com/22291049/84412544-159c9f80-ac18-11ea-8e1b-cd45dd00fd91.png)

and this is my old folder:

![Untitled2](https://user-images.githubusercontent.com/22291049/84412566-1d5c4400-ac18-11ea-9487-0703e7986fa5.png)

**Comment by mguidoti** [comment]
Ok, we are out of shots.

Time to @gsautter to kick in and do his magic.

**Comment by flsimoes** [comment]
> did not work, unfortunately. when I tried to start the QC tool with the console command I use, it said it could not find it
> 
> also, um, my folder is apparently 44 GB. 0_o
> 

That's weird... Did you download the PDF-based version?

> I also noticed that when it asks for a configuration in the beginning, there are only two options (with the installation from your link), while I have 4 options
> 
> ![Untitled](https://user-images.githubusercontent.com/22291049/84409896-7d51eb00-ac16-11ea-8df9-26400561aa77.png)

It should look like in this image

**Comment by flsimoes** [comment]
> for reference, this is the install from the link:
> 
> ![Untitled1](https://user-images.githubusercontent.com/22291049/84412544-159c9f80-ac18-11ea-8e1b-cd45dd00fd91.png)
> 
> and this is my old folder:
> 
> ![Untitled2](https://user-images.githubusercontent.com/22291049/84412566-1d5c4400-ac18-11ea-9487-0703e7986fa5.png)

Some of these folders/files only appear after you have opened GGI and done some things (like batch processing, or transforming a PDF into IMF).

**Comment by gsautter** [comment]
@brokentool If you aren't seeing the remote options in your normal installation, it might be you're lacking the `https://tb.plazi.org/GgServer/Configurations/` in your `ConfigHosts.cnfg` file ... or somehow your HTTPS is broken ... in the latter case, please delete `HttpsCerts/knownCertificates.ks` and restart GGI.
In case the latter doesn't change anything, what's the exact size of your `EasyIO.jar`, and what is its change date?

**Comment by gsautter** [comment]
Otherwise, there might be something going wrong while _assembling_ the context menu, like some kind of error in some contributing gizmo ... the logs should shed some light in that regard.

**Comment by brokentool** [comment]
thank you all for the help, it is much appreciated

- @flsimoes "That's weird... Did you download the PDF-based version?" not sure what you mean by PDF-based version

- @gsautter regarding the remote options, in the version that I downloaded from the link provided above (http://plazi.org/resources/treatmentbank/goldengate-editor/) I get only `Local Master Configuration` and `pro-iBiosphere.editor`. In my old version I have used until now I have the four options from the screenshot I posted above.

==========================================

In the "ConfigHosts.cnfg" file (in my old version) I have:

```
https://srv1.plazi.org/GgServer/Configurations/
http://plazi.cs.umb.edu/GgServer/Configurations/
http://plazi2.cs.umb.edu/GgServer/Configurations/
```

should I add `https://tb.plazi.org/GgServer/Configurations/` before I try other solutions?

==========================================

as for the strange behavior, I notice that when I click on white space and then click somewhere else, it draws the red box, as if I am dragging with the left mouse button pressed, while I am not. it's like it thinks the button is pressed constantly..

**Comment by flsimoes** [comment]
> * @flsimoes "That's weird... Did you download the PDF-based version?" not sure what you mean by PDF-based version

This:
![image](https://user-images.githubusercontent.com/3343086/84417215-b0cb5000-abeb-11ea-9d2b-606b5c3e1e0e.png)

**Comment by gsautter** [comment]
> Otherwise, there might be something going wrong while _assembling_ the context menu, like some kind of error in some contributing gizmo ... the logs should shed some light in that regard.

That looks as if you downloaded GG _Editor_, not GG _Imagine_ ...

**Comment by brokentool** [comment]
@flsimoes no, I downloaded the standard version (facepalm)

aand now I got the PDF one, and IT WORKED like a charm, got menus and everything! happiness and a sleepless night ensues!

sorry for all the bother, guys, and thanks a bunch

@gsautter would you like to see the logs from my old version, if you are interested why the problem occurred in the first place?

**Comment by gsautter** [comment]
@brokentool those old version logs would most likely be very helpful, yes.

**Comment by brokentool** [comment]
here's the Logs folder

[Logs.zip](https://github.com/gsautter/goldengate-qualitycontrol/files/4766241/Logs.zip)

**Comment by gsautter** [comment]
@brokentool The laogs say it all ... looks like you're simply lacking at least one update of the base libraries ... this is the current version: https://tb.plazi.org/GgServer/Downloads/GgImagine-Default.imagine.zip ... does it work with that one?

**Comment by brokentool** [comment]
this file looks identical in size with the one I downloaded from the link provided by @flsimoes, which I can confirm works.

![Untitled](https://user-images.githubusercontent.com/22291049/84421645-8ba70380-ac24-11ea-85c4-e5a79a8689b4.png)

**Comment by gsautter** [comment]
Now if that one does work, you can simply unzip it into your existing installation and replace all the files there, and you should be back to operational condition. The 44GB you mentioned is most likely the IMF cache, which won't be touched be the replacing.

**Comment by brokentool** [comment]
out of curiosity, do I have to? can I just use the new one? just trying to understand

**Comment by gsautter** [comment]
Sure, you can also use the new one ... still, I'm left to wonder how the old one ended up broken, though ... updates _should_ install automatically, also ones for the core libraries in the installation root folder ...

**Comment by brokentool** [comment]
could it be the fact that I missed several updates?

something along these lines was mentioned above: "Yesterday we had to re-install GGI in one of our PCs because it was missing a feature in the template editor (it was a specific case where the PC hadn't been updated gradually over the last 3 months, but still)"

**Comment by gsautter** [comment]
That still leaves me to wonder why the automated update mechanism didn't work ...  well, we might never know ...
